//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTE_BL.VelocifyAPIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://service.leads360.com", ConfigurationName="VelocifyAPIService.ClientServiceSoap")]
    public interface ClientServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddAgent(string username, string password, System.Xml.XmlNode agentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddAgent", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentAsync(string username, string password, System.Xml.XmlNode agentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddAgentToGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddAgentToGroup(string username, string password, System.Xml.XmlNode groupData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddAgentToGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentToGroupAsync(string username, string password, System.Xml.XmlNode groupData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddAgentRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddAgentRole(string username, string password, System.Xml.XmlNode agentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddAgentRole", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentRoleAsync(string username, string password, System.Xml.XmlNode agentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddOptOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddOptOut(string username, string password, string email, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddOptOut", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddOptOutAsync(string username, string password, string email, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddCampaign(string username, string password, string title, string altTitle, int campaignTypeId, string note, decimal costPerLead, bool active, int providerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddCampaign", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddCampaignAsync(string username, string password, string title, string altTitle, int campaignTypeId, string note, decimal costPerLead, bool active, int providerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddField", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddField(string username, string password, string title, int fieldTypeId, string toolTip, bool required, int visibilityTypeId, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddField", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddFieldAsync(string username, string password, string title, int fieldTypeId, string toolTip, bool required, int visibilityTypeId, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddFieldGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddFieldGroup(string username, string password, string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddFieldGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddFieldGroupAsync(string username, string password, string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddLeadAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddLeadAction(string username, string password, int leadId, int actionTypeId, string actionNote);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddLeadAction", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadActionAsync(string username, string password, int leadId, int actionTypeId, string actionNote);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddLeads(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddLeads", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadsAsync(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddLeadsEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddLeadsEx(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddLeadsEx", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadsExAsync(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddDirectMailLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddDirectMailLeads(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddDirectMailLeads", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddDirectMailLeadsAsync(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/DeactivateAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode DeactivateAgent(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/DeactivateAgent", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DeactivateAgentAsync(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/DisableReceiveLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode DisableReceiveLeads(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/DisableReceiveLeads", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DisableReceiveLeadsAsync(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetActionTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetActionTypes(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetActionTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetActionTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAgent(string username, string password, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgent", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentAsync(string username, string password, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAgents(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgents", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgentsInGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAgentsInGroup(string username, string password, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgentsInGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsInGroupAsync(string username, string password, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgentsQualified", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAgentsQualified(string username, string password, int programId, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgentsQualified", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsQualifiedAsync(string username, string password, int programId, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetQualifiedAgents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetQualifiedAgents(string username, string password, int programId, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetQualifiedAgents", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetQualifiedAgentsAsync(string username, string password, int programId, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetCampaigns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCampaigns(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetCampaigns", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetCampaignTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCampaignTypes(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetCampaignTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFieldGroups(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldGroupsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFields(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFields", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFieldTypes(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetGroups(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetGroupsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLastCreatedLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLastCreatedLead(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLastCreatedLead", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLastCreatedLeadAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLastModifiedLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLastModifiedLead(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLastModifiedLead", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLastModifiedLeadAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLead(string username, string password, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLead", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAsync(string username, string password, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadFormTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeadFormTypes(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadFormTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadFormTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeadIds(string username, string password, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadIds", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsAsync(string username, string password, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadIdsEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeadIdsEx(string username, string password, System.DateTime from, System.DateTime to, int scope);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadIdsEx", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsExAsync(string username, string password, System.DateTime from, System.DateTime to, int scope);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadIdsSpan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeadIdsSpan(string username, string password, int fromNowMinutes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadIdsSpan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsSpanAsync(string username, string password, int fromNowMinutes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeads(string username, string password, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeads", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsAsync(string username, string password, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadsByPhone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeadsByPhone(string username, string password, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadsByPhone", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsByPhoneAsync(string username, string password, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadsByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeadsByEmail(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadsByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsByEmailAsync(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadsSpan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeadsSpan(string username, string password, int fromNowMinutes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadsSpan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsSpanAsync(string username, string password, int fromNowMinutes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetMilestones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetMilestones(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetMilestones", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetMilestonesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetPrograms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetPrograms(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetPrograms", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetProgramsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetProviders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetProviders(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetProviders", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetProvidersAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetReportResults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetReportResults(string username, string password, int reportId, System.Xml.XmlNode templateValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetReportResults", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportResultsAsync(string username, string password, int reportId, System.Xml.XmlNode templateValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetReportResultsWithoutFilters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetReportResultsWithoutFilters(string username, string password, int reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetReportResultsWithoutFilters", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportResultsWithoutFiltersAsync(string username, string password, int reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetReports", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetReports(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetReports", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetServerTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GetServerTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetServerTime", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetStatuses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetStatuses(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetStatuses", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetStatusesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetVisibilityTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetVisibilityTypes(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetVisibilityTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetVisibilityTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ModifyAgent(string username, string password, System.Xml.XmlNode agentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyAgent", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyAgentAsync(string username, string password, System.Xml.XmlNode agentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyAgentPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ModifyAgentPassword(string username, string password, string email, string agentPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyAgentPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyAgentPasswordAsync(string username, string password, string email, string agentPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ModifyLeadAgent(string username, string password, int leadId, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadAgent", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadAgentAsync(string username, string password, int leadId, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ModifyLeadCampaign(string username, string password, int leadId, int campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadCampaign", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadCampaignAsync(string username, string password, int leadId, int campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadField", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ModifyLeadField(string username, string password, int leadId, int fieldId, string newValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadField", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadFieldAsync(string username, string password, int leadId, int fieldId, string newValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ModifyLeads(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeads", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadsAsync(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ModifyLeadStatus(string username, string password, int leadId, int statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadStatusAsync(string username, string password, int leadId, int statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/RemoveCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode RemoveCampaign(string username, string password, int campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/RemoveCampaign", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveCampaignAsync(string username, string password, int campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/RemoveLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode RemoveLead(string username, string password, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/RemoveLead", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveLeadAsync(string username, string password, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/CopyLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CopyLead(string username, string password, int LeadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/CopyLead", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CopyLeadAsync(string username, string password, int LeadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AssignViaDistribution", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AssignViaDistribution(string username, string password, int leadId, int programId, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AssignViaDistribution", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AssignViaDistributionAsync(string username, string password, int leadId, int programId, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadAndQualifiedAgentsByPhone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeadAndQualifiedAgentsByPhone(string username, string password, string phone, int programId, int campaignId, int firstFieldId, string firstFieldValue, int secondFieldId, string secondFieldValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadAndQualifiedAgentsByPhone", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAndQualifiedAgentsByPhoneAsync(string username, string password, string phone, int programId, int campaignId, int firstFieldId, string firstFieldValue, int secondFieldId, string secondFieldValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadAndQualifiedAgentsByPhoneWithLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLeadAndQualifiedAgentsByPhoneWithLead(string username, string password, string phone, int programId, int campaignId, GTE_BL.VelocifyAPIService.FieldValue[] fields);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadAndQualifiedAgentsByPhoneWithLead", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAndQualifiedAgentsByPhoneWithLeadAsync(string username, string password, string phone, int programId, int campaignId, GTE_BL.VelocifyAPIService.FieldValue[] fields);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldsSalesforce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFieldsSalesforce(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldsSalesforce", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldsSalesforceAsync(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldTypesSalesforce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFieldTypesSalesforce(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldTypesSalesforce", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldTypesSalesforceAsync(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldGroupsSalesforce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetFieldGroupsSalesforce(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldGroupsSalesforce", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldGroupsSalesforceAsync(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetSalesforceMappings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetSalesforceMappings(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetSalesforceMappings", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetSalesforceMappingsAsync(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifySalesforceMappings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ModifySalesforceMappings(string username, string sessionId, string url, string xmlText);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifySalesforceMappings", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifySalesforceMappingsAsync(string username, string sessionId, string url, string xmlText);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifySalesforceUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ModifySalesforceUsername(string username, string password, string salesforceUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifySalesforceUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifySalesforceUsernameAsync(string username, string password, string salesforceUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://service.leads360.com")]
    public partial class FieldValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fieldIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FieldId {
            get {
                return this.fieldIdField;
            }
            set {
                this.fieldIdField = value;
                this.RaisePropertyChanged("FieldId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientServiceSoapChannel : GTE_BL.VelocifyAPIService.ClientServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceSoapClient : System.ServiceModel.ClientBase<GTE_BL.VelocifyAPIService.ClientServiceSoap>, GTE_BL.VelocifyAPIService.ClientServiceSoap {
        
        public ClientServiceSoapClient() {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode AddAgent(string username, string password, System.Xml.XmlNode agentData) {
            return base.Channel.AddAgent(username, password, agentData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentAsync(string username, string password, System.Xml.XmlNode agentData) {
            return base.Channel.AddAgentAsync(username, password, agentData);
        }
        
        public System.Xml.XmlNode AddAgentToGroup(string username, string password, System.Xml.XmlNode groupData) {
            return base.Channel.AddAgentToGroup(username, password, groupData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentToGroupAsync(string username, string password, System.Xml.XmlNode groupData) {
            return base.Channel.AddAgentToGroupAsync(username, password, groupData);
        }
        
        public System.Xml.XmlNode AddAgentRole(string username, string password, System.Xml.XmlNode agentData) {
            return base.Channel.AddAgentRole(username, password, agentData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentRoleAsync(string username, string password, System.Xml.XmlNode agentData) {
            return base.Channel.AddAgentRoleAsync(username, password, agentData);
        }
        
        public System.Xml.XmlNode AddOptOut(string username, string password, string email, int leadId) {
            return base.Channel.AddOptOut(username, password, email, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddOptOutAsync(string username, string password, string email, int leadId) {
            return base.Channel.AddOptOutAsync(username, password, email, leadId);
        }
        
        public System.Xml.XmlNode AddCampaign(string username, string password, string title, string altTitle, int campaignTypeId, string note, decimal costPerLead, bool active, int providerId) {
            return base.Channel.AddCampaign(username, password, title, altTitle, campaignTypeId, note, costPerLead, active, providerId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddCampaignAsync(string username, string password, string title, string altTitle, int campaignTypeId, string note, decimal costPerLead, bool active, int providerId) {
            return base.Channel.AddCampaignAsync(username, password, title, altTitle, campaignTypeId, note, costPerLead, active, providerId);
        }
        
        public System.Xml.XmlNode AddField(string username, string password, string title, int fieldTypeId, string toolTip, bool required, int visibilityTypeId, int groupId) {
            return base.Channel.AddField(username, password, title, fieldTypeId, toolTip, required, visibilityTypeId, groupId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddFieldAsync(string username, string password, string title, int fieldTypeId, string toolTip, bool required, int visibilityTypeId, int groupId) {
            return base.Channel.AddFieldAsync(username, password, title, fieldTypeId, toolTip, required, visibilityTypeId, groupId);
        }
        
        public System.Xml.XmlNode AddFieldGroup(string username, string password, string title) {
            return base.Channel.AddFieldGroup(username, password, title);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddFieldGroupAsync(string username, string password, string title) {
            return base.Channel.AddFieldGroupAsync(username, password, title);
        }
        
        public System.Xml.XmlNode AddLeadAction(string username, string password, int leadId, int actionTypeId, string actionNote) {
            return base.Channel.AddLeadAction(username, password, leadId, actionTypeId, actionNote);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadActionAsync(string username, string password, int leadId, int actionTypeId, string actionNote) {
            return base.Channel.AddLeadActionAsync(username, password, leadId, actionTypeId, actionNote);
        }
        
        public System.Xml.XmlNode AddLeads(string username, string password, System.Xml.XmlNode leads) {
            return base.Channel.AddLeads(username, password, leads);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadsAsync(string username, string password, System.Xml.XmlNode leads) {
            return base.Channel.AddLeadsAsync(username, password, leads);
        }
        
        public System.Xml.XmlNode AddLeadsEx(string username, string password, System.Xml.XmlNode leads) {
            return base.Channel.AddLeadsEx(username, password, leads);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadsExAsync(string username, string password, System.Xml.XmlNode leads) {
            return base.Channel.AddLeadsExAsync(username, password, leads);
        }
        
        public System.Xml.XmlNode AddDirectMailLeads(string username, string password, System.Xml.XmlNode leads) {
            return base.Channel.AddDirectMailLeads(username, password, leads);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddDirectMailLeadsAsync(string username, string password, System.Xml.XmlNode leads) {
            return base.Channel.AddDirectMailLeadsAsync(username, password, leads);
        }
        
        public System.Xml.XmlNode DeactivateAgent(string username, string password, string email) {
            return base.Channel.DeactivateAgent(username, password, email);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DeactivateAgentAsync(string username, string password, string email) {
            return base.Channel.DeactivateAgentAsync(username, password, email);
        }
        
        public System.Xml.XmlNode DisableReceiveLeads(string username, string password, string email) {
            return base.Channel.DisableReceiveLeads(username, password, email);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DisableReceiveLeadsAsync(string username, string password, string email) {
            return base.Channel.DisableReceiveLeadsAsync(username, password, email);
        }
        
        public System.Xml.XmlNode GetActionTypes(string username, string password) {
            return base.Channel.GetActionTypes(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetActionTypesAsync(string username, string password) {
            return base.Channel.GetActionTypesAsync(username, password);
        }
        
        public System.Xml.XmlNode GetAgent(string username, string password, int agentId) {
            return base.Channel.GetAgent(username, password, agentId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentAsync(string username, string password, int agentId) {
            return base.Channel.GetAgentAsync(username, password, agentId);
        }
        
        public System.Xml.XmlNode GetAgents(string username, string password) {
            return base.Channel.GetAgents(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsAsync(string username, string password) {
            return base.Channel.GetAgentsAsync(username, password);
        }
        
        public System.Xml.XmlNode GetAgentsInGroup(string username, string password, int groupId) {
            return base.Channel.GetAgentsInGroup(username, password, groupId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsInGroupAsync(string username, string password, int groupId) {
            return base.Channel.GetAgentsInGroupAsync(username, password, groupId);
        }
        
        public System.Xml.XmlNode GetAgentsQualified(string username, string password, int programId, int leadId) {
            return base.Channel.GetAgentsQualified(username, password, programId, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsQualifiedAsync(string username, string password, int programId, int leadId) {
            return base.Channel.GetAgentsQualifiedAsync(username, password, programId, leadId);
        }
        
        public System.Xml.XmlNode GetQualifiedAgents(string username, string password, int programId, int leadId) {
            return base.Channel.GetQualifiedAgents(username, password, programId, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetQualifiedAgentsAsync(string username, string password, int programId, int leadId) {
            return base.Channel.GetQualifiedAgentsAsync(username, password, programId, leadId);
        }
        
        public System.Xml.XmlNode GetCampaigns(string username, string password) {
            return base.Channel.GetCampaigns(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignsAsync(string username, string password) {
            return base.Channel.GetCampaignsAsync(username, password);
        }
        
        public System.Xml.XmlNode GetCampaignTypes(string username, string password) {
            return base.Channel.GetCampaignTypes(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignTypesAsync(string username, string password) {
            return base.Channel.GetCampaignTypesAsync(username, password);
        }
        
        public System.Xml.XmlNode GetFieldGroups(string username, string password) {
            return base.Channel.GetFieldGroups(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldGroupsAsync(string username, string password) {
            return base.Channel.GetFieldGroupsAsync(username, password);
        }
        
        public System.Xml.XmlNode GetFields(string username, string password) {
            return base.Channel.GetFields(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldsAsync(string username, string password) {
            return base.Channel.GetFieldsAsync(username, password);
        }
        
        public System.Xml.XmlNode GetFieldTypes(string username, string password) {
            return base.Channel.GetFieldTypes(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldTypesAsync(string username, string password) {
            return base.Channel.GetFieldTypesAsync(username, password);
        }
        
        public System.Xml.XmlNode GetGroups(string username, string password) {
            return base.Channel.GetGroups(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetGroupsAsync(string username, string password) {
            return base.Channel.GetGroupsAsync(username, password);
        }
        
        public System.Xml.XmlNode GetLastCreatedLead(string username, string password) {
            return base.Channel.GetLastCreatedLead(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLastCreatedLeadAsync(string username, string password) {
            return base.Channel.GetLastCreatedLeadAsync(username, password);
        }
        
        public System.Xml.XmlNode GetLastModifiedLead(string username, string password) {
            return base.Channel.GetLastModifiedLead(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLastModifiedLeadAsync(string username, string password) {
            return base.Channel.GetLastModifiedLeadAsync(username, password);
        }
        
        public System.Xml.XmlNode GetLead(string username, string password, int leadId) {
            return base.Channel.GetLead(username, password, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAsync(string username, string password, int leadId) {
            return base.Channel.GetLeadAsync(username, password, leadId);
        }
        
        public System.Xml.XmlNode GetLeadFormTypes(string username, string password) {
            return base.Channel.GetLeadFormTypes(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadFormTypesAsync(string username, string password) {
            return base.Channel.GetLeadFormTypesAsync(username, password);
        }
        
        public System.Xml.XmlNode GetLeadIds(string username, string password, System.DateTime from, System.DateTime to) {
            return base.Channel.GetLeadIds(username, password, from, to);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsAsync(string username, string password, System.DateTime from, System.DateTime to) {
            return base.Channel.GetLeadIdsAsync(username, password, from, to);
        }
        
        public System.Xml.XmlNode GetLeadIdsEx(string username, string password, System.DateTime from, System.DateTime to, int scope) {
            return base.Channel.GetLeadIdsEx(username, password, from, to, scope);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsExAsync(string username, string password, System.DateTime from, System.DateTime to, int scope) {
            return base.Channel.GetLeadIdsExAsync(username, password, from, to, scope);
        }
        
        public System.Xml.XmlNode GetLeadIdsSpan(string username, string password, int fromNowMinutes) {
            return base.Channel.GetLeadIdsSpan(username, password, fromNowMinutes);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsSpanAsync(string username, string password, int fromNowMinutes) {
            return base.Channel.GetLeadIdsSpanAsync(username, password, fromNowMinutes);
        }
        
        public System.Xml.XmlNode GetLeads(string username, string password, System.DateTime from, System.DateTime to) {
            return base.Channel.GetLeads(username, password, from, to);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsAsync(string username, string password, System.DateTime from, System.DateTime to) {
            return base.Channel.GetLeadsAsync(username, password, from, to);
        }
        
        public System.Xml.XmlNode GetLeadsByPhone(string username, string password, string phone) {
            return base.Channel.GetLeadsByPhone(username, password, phone);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsByPhoneAsync(string username, string password, string phone) {
            return base.Channel.GetLeadsByPhoneAsync(username, password, phone);
        }
        
        public System.Xml.XmlNode GetLeadsByEmail(string username, string password, string email) {
            return base.Channel.GetLeadsByEmail(username, password, email);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsByEmailAsync(string username, string password, string email) {
            return base.Channel.GetLeadsByEmailAsync(username, password, email);
        }
        
        public System.Xml.XmlNode GetLeadsSpan(string username, string password, int fromNowMinutes) {
            return base.Channel.GetLeadsSpan(username, password, fromNowMinutes);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsSpanAsync(string username, string password, int fromNowMinutes) {
            return base.Channel.GetLeadsSpanAsync(username, password, fromNowMinutes);
        }
        
        public System.Xml.XmlNode GetMilestones(string username, string password) {
            return base.Channel.GetMilestones(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetMilestonesAsync(string username, string password) {
            return base.Channel.GetMilestonesAsync(username, password);
        }
        
        public System.Xml.XmlNode GetPrograms(string username, string password) {
            return base.Channel.GetPrograms(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetProgramsAsync(string username, string password) {
            return base.Channel.GetProgramsAsync(username, password);
        }
        
        public System.Xml.XmlNode GetProviders(string username, string password) {
            return base.Channel.GetProviders(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetProvidersAsync(string username, string password) {
            return base.Channel.GetProvidersAsync(username, password);
        }
        
        public System.Xml.XmlNode GetReportResults(string username, string password, int reportId, System.Xml.XmlNode templateValues) {
            return base.Channel.GetReportResults(username, password, reportId, templateValues);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportResultsAsync(string username, string password, int reportId, System.Xml.XmlNode templateValues) {
            return base.Channel.GetReportResultsAsync(username, password, reportId, templateValues);
        }
        
        public System.Xml.XmlNode GetReportResultsWithoutFilters(string username, string password, int reportId) {
            return base.Channel.GetReportResultsWithoutFilters(username, password, reportId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportResultsWithoutFiltersAsync(string username, string password, int reportId) {
            return base.Channel.GetReportResultsWithoutFiltersAsync(username, password, reportId);
        }
        
        public System.Xml.XmlNode GetReports(string username, string password) {
            return base.Channel.GetReports(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportsAsync(string username, string password) {
            return base.Channel.GetReportsAsync(username, password);
        }
        
        public System.DateTime GetServerTime() {
            return base.Channel.GetServerTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync() {
            return base.Channel.GetServerTimeAsync();
        }
        
        public System.Xml.XmlNode GetStatuses(string username, string password) {
            return base.Channel.GetStatuses(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetStatusesAsync(string username, string password) {
            return base.Channel.GetStatusesAsync(username, password);
        }
        
        public System.Xml.XmlNode GetVisibilityTypes(string username, string password) {
            return base.Channel.GetVisibilityTypes(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetVisibilityTypesAsync(string username, string password) {
            return base.Channel.GetVisibilityTypesAsync(username, password);
        }
        
        public System.Xml.XmlNode ModifyAgent(string username, string password, System.Xml.XmlNode agentData) {
            return base.Channel.ModifyAgent(username, password, agentData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyAgentAsync(string username, string password, System.Xml.XmlNode agentData) {
            return base.Channel.ModifyAgentAsync(username, password, agentData);
        }
        
        public System.Xml.XmlNode ModifyAgentPassword(string username, string password, string email, string agentPassword) {
            return base.Channel.ModifyAgentPassword(username, password, email, agentPassword);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyAgentPasswordAsync(string username, string password, string email, string agentPassword) {
            return base.Channel.ModifyAgentPasswordAsync(username, password, email, agentPassword);
        }
        
        public System.Xml.XmlNode ModifyLeadAgent(string username, string password, int leadId, int agentId) {
            return base.Channel.ModifyLeadAgent(username, password, leadId, agentId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadAgentAsync(string username, string password, int leadId, int agentId) {
            return base.Channel.ModifyLeadAgentAsync(username, password, leadId, agentId);
        }
        
        public System.Xml.XmlNode ModifyLeadCampaign(string username, string password, int leadId, int campaignId) {
            return base.Channel.ModifyLeadCampaign(username, password, leadId, campaignId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadCampaignAsync(string username, string password, int leadId, int campaignId) {
            return base.Channel.ModifyLeadCampaignAsync(username, password, leadId, campaignId);
        }
        
        public System.Xml.XmlNode ModifyLeadField(string username, string password, int leadId, int fieldId, string newValue) {
            return base.Channel.ModifyLeadField(username, password, leadId, fieldId, newValue);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadFieldAsync(string username, string password, int leadId, int fieldId, string newValue) {
            return base.Channel.ModifyLeadFieldAsync(username, password, leadId, fieldId, newValue);
        }
        
        public System.Xml.XmlNode ModifyLeads(string username, string password, System.Xml.XmlNode leads) {
            return base.Channel.ModifyLeads(username, password, leads);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadsAsync(string username, string password, System.Xml.XmlNode leads) {
            return base.Channel.ModifyLeadsAsync(username, password, leads);
        }
        
        public System.Xml.XmlNode ModifyLeadStatus(string username, string password, int leadId, int statusId) {
            return base.Channel.ModifyLeadStatus(username, password, leadId, statusId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadStatusAsync(string username, string password, int leadId, int statusId) {
            return base.Channel.ModifyLeadStatusAsync(username, password, leadId, statusId);
        }
        
        public System.Xml.XmlNode RemoveCampaign(string username, string password, int campaignId) {
            return base.Channel.RemoveCampaign(username, password, campaignId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveCampaignAsync(string username, string password, int campaignId) {
            return base.Channel.RemoveCampaignAsync(username, password, campaignId);
        }
        
        public System.Xml.XmlNode RemoveLead(string username, string password, int leadId) {
            return base.Channel.RemoveLead(username, password, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveLeadAsync(string username, string password, int leadId) {
            return base.Channel.RemoveLeadAsync(username, password, leadId);
        }
        
        public System.Xml.XmlNode CopyLead(string username, string password, int LeadId) {
            return base.Channel.CopyLead(username, password, LeadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CopyLeadAsync(string username, string password, int LeadId) {
            return base.Channel.CopyLeadAsync(username, password, LeadId);
        }
        
        public System.Xml.XmlNode AssignViaDistribution(string username, string password, int leadId, int programId, int agentId) {
            return base.Channel.AssignViaDistribution(username, password, leadId, programId, agentId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AssignViaDistributionAsync(string username, string password, int leadId, int programId, int agentId) {
            return base.Channel.AssignViaDistributionAsync(username, password, leadId, programId, agentId);
        }
        
        public System.Xml.XmlNode GetLeadAndQualifiedAgentsByPhone(string username, string password, string phone, int programId, int campaignId, int firstFieldId, string firstFieldValue, int secondFieldId, string secondFieldValue) {
            return base.Channel.GetLeadAndQualifiedAgentsByPhone(username, password, phone, programId, campaignId, firstFieldId, firstFieldValue, secondFieldId, secondFieldValue);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAndQualifiedAgentsByPhoneAsync(string username, string password, string phone, int programId, int campaignId, int firstFieldId, string firstFieldValue, int secondFieldId, string secondFieldValue) {
            return base.Channel.GetLeadAndQualifiedAgentsByPhoneAsync(username, password, phone, programId, campaignId, firstFieldId, firstFieldValue, secondFieldId, secondFieldValue);
        }
        
        public System.Xml.XmlNode GetLeadAndQualifiedAgentsByPhoneWithLead(string username, string password, string phone, int programId, int campaignId, GTE_BL.VelocifyAPIService.FieldValue[] fields) {
            return base.Channel.GetLeadAndQualifiedAgentsByPhoneWithLead(username, password, phone, programId, campaignId, fields);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAndQualifiedAgentsByPhoneWithLeadAsync(string username, string password, string phone, int programId, int campaignId, GTE_BL.VelocifyAPIService.FieldValue[] fields) {
            return base.Channel.GetLeadAndQualifiedAgentsByPhoneWithLeadAsync(username, password, phone, programId, campaignId, fields);
        }
        
        public System.Xml.XmlNode GetFieldsSalesforce(string username, string sessionId, string url) {
            return base.Channel.GetFieldsSalesforce(username, sessionId, url);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldsSalesforceAsync(string username, string sessionId, string url) {
            return base.Channel.GetFieldsSalesforceAsync(username, sessionId, url);
        }
        
        public System.Xml.XmlNode GetFieldTypesSalesforce(string username, string sessionId, string url) {
            return base.Channel.GetFieldTypesSalesforce(username, sessionId, url);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldTypesSalesforceAsync(string username, string sessionId, string url) {
            return base.Channel.GetFieldTypesSalesforceAsync(username, sessionId, url);
        }
        
        public System.Xml.XmlNode GetFieldGroupsSalesforce(string username, string sessionId, string url) {
            return base.Channel.GetFieldGroupsSalesforce(username, sessionId, url);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldGroupsSalesforceAsync(string username, string sessionId, string url) {
            return base.Channel.GetFieldGroupsSalesforceAsync(username, sessionId, url);
        }
        
        public System.Xml.XmlNode GetSalesforceMappings(string username, string sessionId, string url) {
            return base.Channel.GetSalesforceMappings(username, sessionId, url);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetSalesforceMappingsAsync(string username, string sessionId, string url) {
            return base.Channel.GetSalesforceMappingsAsync(username, sessionId, url);
        }
        
        public System.Xml.XmlNode ModifySalesforceMappings(string username, string sessionId, string url, string xmlText) {
            return base.Channel.ModifySalesforceMappings(username, sessionId, url, xmlText);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifySalesforceMappingsAsync(string username, string sessionId, string url, string xmlText) {
            return base.Channel.ModifySalesforceMappingsAsync(username, sessionId, url, xmlText);
        }
        
        public System.Xml.XmlNode ModifySalesforceUsername(string username, string password, string salesforceUsername) {
            return base.Channel.ModifySalesforceUsername(username, password, salesforceUsername);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifySalesforceUsernameAsync(string username, string password, string salesforceUsername) {
            return base.Channel.ModifySalesforceUsernameAsync(username, password, salesforceUsername);
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync() {
            return base.Channel.GetVersionAsync();
        }
    }
}
